.\" Copyright 2015 Alexej Magura
.\"
.\" Copying and distribution of this file, with or without modification,
.\" are permitted in any medium without royalty provided the copyright
.\" notice and this notice are preserved.  This file is offered as-is,
.\" without any warranty.
.TH ZBATT 1 "28 April 2015"
.SH NAME
zbatt \- textually represent battery levels
.SH SYNOPSIS
\fBzbatt\fR [\fIOPTION\fP]...
.SH OPTIONS
Mandatory arguments to long options are mandatory for short options too.

\fB-h\fR, \fB--help\fR
